# Generated by Django 4.2.4 on 2023-08-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('1', '본인'), ('2', '가족'), ('3', '기타')], max_length=2, verbose_name='관계')),
                ('date', models.DateTimeField(verbose_name='사고날짜')),
                ('type', models.TextField(verbose_name='유형')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사고자')),
            ],
        ),
    ]
