# Generated by Django 4.2.4 on 2023-08-10 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relation',
            field=models.CharField(choices=[('본인', '1'), ('가족', '2'), ('기타', '3')], max_length=2, verbose_name='관계'),
        ),
        migrations.AlterField(
            model_name='report',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
