# Generated by Django 4.2.4 on 2023-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relation',
            field=models.CharField(choices=[('본인', '1'), ('가족', '2'), ('기타', '3')], max_length=2, verbose_name='관계'),
        ),
    ]
