# Generated by Django 4.2.4 on 2023-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relation',
            field=models.CharField(choices=[('me', '1'), ('family', '2'), ('rel-etc', '3')], max_length=10, verbose_name='관계'),
        ),
    ]
