# Generated by Django 4.2.4 on 2023-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='center',
            field=models.CharField(default='미정', max_length=50),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='introduction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='letter',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
