# Generated by Django 4.2.4 on 2023-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='is_neutralized',
            field=models.IntegerField(default=1),
        ),
    ]
