# Generated by Django 4.2.4 on 2023-08-10 17:18

from django.db import migrations, models
import django.db.models.deletion
import todays.models


class Migration(migrations.Migration):

    dependencies = [
        ('todays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='today_id',
        ),
        migrations.AddField(
            model_name='images',
            name='today',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='todays.today'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=todays.models.image_upload_path, verbose_name='이미지'),
        ),
    ]
